swagger: "2.0"
info:
  version: "1.0.1"
  title: "Mechanic Shop API"
  description: "API for managing customers, mechanics, parts, and service tickets."

host: "mechanics-api.onrender.com"
basePath: "/"
schemes:
  - "https"

consumes:
  - "application/json"
produces:
  - "application/json"

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: |
      JWT Authorization header using the Bearer scheme.
      Example: "Bearer {token}"

tags:
  - name: Customers
    description: "Customer management"
  - name: Mechanics
    description: "Mechanic registration, login, and management"
  - name: Inventory
    description: "Parts/Inventory management"
  - name: Service Tickets
    description: "Service ticket creation and tracking"
  - name: Negative Tests
    description: "Endpoints for intentional failure scenarios"

paths:
  /customers:
    post:
      tags: [Customers]
      summary: Create a new customer
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Customer"
          examples:
            application/json:
              name: "Alice Johnson"
              email: "alice@example.com"
              phone: "555-1234"
              car: "Ford Focus"
      responses:
        "201": { description: Customer created }
        "400": { description: Bad Request }
        "409": { description: Conflict (email exists) }

    get:
      tags: [Customers]
      summary: Get all customers
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: List of customers }

  /customers/search:
    get:
      tags: [Customers]
      summary: Search customer by email
      parameters:
        - name: email
          in: query
          required: true
          type: string
          example: "alice@example.com"
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: Customer found }
        "404": { description: Customer not found }

  /customers/{id}:
    put:
      tags: [Customers]
      summary: Update a customer
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Customer"
          examples:
            application/json:
              name: "Alice Updated"
              email: "alice.new@example.com"
              phone: "555-5678"
              car: "Nissan Altima"
      responses:
        "200": { description: Customer updated }
        "404": { description: Customer not found }

    delete:
      tags: [Customers]
      summary: Delete a customer
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "200": { description: Customer deleted }
        "404": { description: Customer not found }

  /mechanics/ping:
    get:
      tags: [Mechanics]
      summary: Health check endpoint
      responses:
        "200": { description: Pong }

  /mechanics/login:
    post:
      tags: [Mechanics]
      summary: Login mechanic
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Login"
          examples:
            application/json:
              email: "mike@example.com"
              password: "password1"
      responses:
        "200": { description: Successful login (returns JWT token) }
        "400": { description: Invalid credentials }

  /mechanics:
    get:
      tags: [Mechanics]
      summary: Get all mechanics
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: List of mechanics }
        "401": { description: Unauthorized }

    post:
      tags: [Mechanics]
      summary: Create mechanic
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Mechanic"
          examples:
            application/json:
              name: "New Mechanic"
              email: "new.mech@example.com"
              password: "newpass123"
              specialty: "Diagnostics"
      responses:
        "201": { description: Mechanic created }
        "400": { description: Invalid input }
        "409": { description: Email exists }

  /mechanics/{id}:
    put:
      tags: [Mechanics]
      summary: Update mechanic
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Mechanic"
          examples:
            application/json:
              name: "Mike Updated"
              specialty: "Engine"
      responses:
        "200": { description: Mechanic updated }
        "404": { description: Mechanic not found }

    delete:
      tags: [Mechanics]
      summary: Delete mechanic
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "200": { description: Mechanic deleted }
        "404": { description: Mechanic not found }

  /mechanics/my-tickets:
    get:
      tags: [Mechanics]
      summary: Get tickets assigned to mechanic
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: Tickets for mechanic }

  /mechanics/top:
    get:
      tags: [Mechanics]
      summary: Get mechanic with most tickets
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: Mechanic with most tickets }

  /mechanics/ticket-count:
    get:
      tags: [Mechanics]
      summary: Get ticket count by mechanic
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: Ticket count by mechanic }

  /inventory:
    post:
      tags: [Inventory]
      summary: Create part
      security: [{ BearerAuth: [] }]
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Inventory"
          examples:
            application/json:
              name: "Brake Pads"
              price: 50.0
      responses:
        "201": { description: Part created }
        "400": { description: Bad input }

    get:
      tags: [Inventory]
      summary: Get all parts
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: List of parts }

  /inventory/{id}:
    get:
      tags: [Inventory]
      summary: Get part by ID
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: Part found }
        "404": { description: Part not found }

    put:
      tags: [Inventory]
      summary: Update part
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Inventory"
          examples:
            application/json:
              name: "Rotor"
              price: 120.0
      responses:
        "200": { description: Part updated }
        "404": { description: Part not found }

    delete:
      tags: [Inventory]
      summary: Delete part
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "200": { description: Part deleted }
        "404": { description: Part not found }

  /service_tickets:
    post:
      tags: [Service Tickets]
      summary: Create service ticket
      security: [{ BearerAuth: [] }]
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/ServiceTicket"
          examples:
            application/json:
              description: "Brake replacement"
              customer_id: 1
              status: "Open"
      responses:
        "201": { description: Ticket created }
        "400": { description: Invalid data }
        "401": { description: Unauthorized }

    get:
      tags: [Service Tickets]
      summary: Get all tickets
      security: [{ BearerAuth: [] }]
      responses:
        "200": { description: List of tickets }
        "401": { description: Unauthorized }

  /service_tickets/{id}:
    put:
      tags: [Service Tickets]
      summary: Update ticket
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          schema:
            $ref: "#/definitions/ServiceTicket"
          examples:
            application/json:
              description: "Brake + rotor replacement"
              status: "In Progress"
      responses:
        "200": { description: Ticket updated }
        "404": { description: Ticket not found }

    delete:
      tags: [Service Tickets]
      summary: Delete ticket
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "200": { description: Ticket deleted }
        "404": { description: Ticket not found }

  /service_tickets/{id}/assign/{mechanic_id}:
    post:
      tags: [Service Tickets]
      summary: Assign mechanic to ticket
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: mechanic_id
          in: path
          required: true
          type: integer
      responses:
        "200": { description: Mechanic assigned }
        "404": { description: Ticket or mechanic not found }

  /service_tickets/{id}/parts:
    post:
      tags: [Service Tickets]
      summary: Add part to ticket
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          schema:
            type: object
            required: [part_id]
            properties:
              part_id:
                type: integer
          examples:
            application/json:
              part_id: 1
      responses:
        "200": { description: Part added to ticket }
        "404": { description: Ticket or part not found }

  /negative/customers/bad_request:
    post:
      tags: [Negative Tests]
      summary: Create customer missing email (should fail)
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Customer"
          examples:
            application/json:
              name: "Missing Email"
              phone: "555-0000"
              car: "Toyota"
      responses:
        "400": { description: Intentional bad request }

  /negative/mechanics/unauthorized:
    get:
      tags: [Negative Tests]
      summary: Get mechanics without token (should fail)
      responses:
        "401": { description: Intentional unauthorized }

definitions:
  Customer:
    type: object
    required:
      - name
      - email
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
        example: "John Doe"
      email:
        type: string
        example: "john@example.com"
      phone:
        type: string
        example: "555-1111"
      car:
        type: string
        example: "Honda Civic"

  Mechanic:
    type: object
    required:
      - name
      - email
      - password
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
        example: "Mike Wrench"
      email:
        type: string
        example: "mike@example.com"
      password:
        type: string
        example: "password1"
      specialty:
        type: string
        example: "Engine"

  Inventory:
    type: object
    required:
      - name
      - price
    properties:
      id:
        type: integer
        readOnly: true
      name:
        type: string
        example: "Brake Pads"
      price:
        type: number
        format: float
        example: 59.99

  ServiceTicket:
    type: object
    required:
      - customer_id
      - description
      - status
    properties:
      id:
        type: integer
        readOnly: true
      customer_id:
        type: integer
        example: 1
      description:
        type: string
        example: "Oil change"
      status:
        type: string
        example: "Open"

  Login:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        example: "mike@example.com"
      password:
        type: string
        example: "password1"
