"""fresh schema

Revision ID: c931624d9416
Revises: 
Create Date: 2025-08-23 03:07:12.198040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c931624d9416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('service_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_service_ticket_customer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_mechanic',
    sa.Column('service_ticket_id', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], name='fk_service_mechanic_mechanic_id'),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], name='fk_service_mechanic_ticket_id')
    )
    op.create_table('service_ticket_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_ticket_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name='fk_service_ticket_inventory_inventory_id'),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_ticket.id'], name='fk_service_ticket_inventory_ticket_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_ticket_inventory')
    op.drop_table('service_mechanic')
    op.drop_table('service_ticket')
    op.drop_table('mechanic')
    op.drop_table('inventory')
    op.drop_table('customer')
    # ### end Alembic commands ###
